// <auto-generated />
namespace OnlineContacts.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initMigrationCreatTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initMigrationCreatTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202003070339534_initMigrationCreatTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
